CREATE TABLE users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    balance bigint
);

INSERT INTO users (balance) VALUES ('500000');
INSERT INTO users (balance) VALUES ('100');
INSERT INTO users (balance) VALUES ('0');
INSERT INTO users (balance) VALUES ('-400');

CREATE TABLE operations (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint references users(id) ON DELETE SET NULL,
    operation_type varchar(50),
    amount bigint,
    operation_date date
);

INSERT INTO operations (user_id, operation_type, amount, operation_date) VALUES
('1', 'OUTGOING_TRANSFER', '10000', '2020-01-01');
INSERT INTO operations (user_id, operation_type, amount, operation_date) VALUES
('2', 'INCOMING_TRANSFER', '10000', '2020-01-01');
INSERT INTO operations (user_id, operation_type, amount, operation_date) VALUES
('1', 'DEPOSIT', '5000', '2023-02-02');
INSERT INTO operations (user_id, operation_type, amount, operation_date) VALUES
('1', 'WITHDRAW', '3000', '2023-02-03');



