CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    balance BIGINT
);

INSERT INTO users (balance) VALUES ('0');
INSERT INTO users (balance) VALUES ('100');
INSERT INTO users (balance) VALUES ('50000');
INSERT INTO users (balance) VALUES ('-400');

